import request from "./request";
export const getBatches = (p) => request.get("/module3/batches", { params: p });
export const getStudentBatches = () => request.get("/module3/student-batches");
export const ensureStudentExampleForm = (d) => request.post("/module3/student/example-form", d);
export const deleteStudentExampleForm = (batchId) => request.delete(`/module3/student/example-form/${batchId}`);
export const uploadStudentSupportMaterials = (formData) => request.post("/module3/student/support-materials", formData, { headers: { "Content-Type": "multipart/form-data" } });
export const createBatch = (d) => request.post("/module3/batches", d);
export const updateBatch = (id, d) => request.put(`/module3/batches/${id}`, d);
export const updateBatchStatus = (id, d) => request.put(`/module3/batches/${id}/status`, d);
export const deleteBatch = (id) => request.delete(`/module3/batches/${id}`);
export const getSettings = () => request.get("/module3/settings");
export const updateSettings = (d) => request.put("/module3/settings", d);
export const getScopeOptions = () => request.get("/module3/scope-options");
export const getStudents = () => request.get("/module3/students");
export const updateCounselorScope = (d) => request.put("/module3/counselor/scope", d);
export const setAssessmentMember = (id, d) => request.put(`/module3/students/${id}/member`, d);
export const getMyMaterials = (p) => request.get("/module3/materials", { params: p });
export const getFormDetail = (id) => request.get(`/module3/forms/${id}`);
export const getFormDocumentPreview = (id) => request.get(`/module3/forms/${id}/document/preview`);
export const downloadFormDocument = (id) => request.get(`/module3/forms/${id}/document/download`, { responseType: "blob" });
export const setFormLevel = (id, d) => request.put(`/module3/forms/${id}/level`, d);
export const reviewMaterial = (id, d) => request.put(`/module3/materials/${id}/review`, d);
export const submitObjection = (id, d) => request.post(`/module3/forms/${id}/objections`, d);
export const getPendingReviews = () => request.get("/module3/pending");
export const getStatistics = (p) => request.get("/module3/statistics", { params: p });
export const exportExcel = (d) => request.post("/module3/export", d, { responseType: "blob" });
export const getLogs = () => request.get("/module3/logs");
export const adminListUsers = (p) => request.get("/module3/admin/users", { params: p });
export const adminCreateStudent = (d) => request.post("/module3/admin/accounts/student", d);
export const adminImportStudents = (d) => request.post("/module3/admin/accounts/student-import", d);
export const adminGenerateAccounts = (d) => request.post("/module3/admin/accounts/generate", d);
export const adminResetPassword = (d) => request.put("/module3/admin/accounts/reset-password", d);
export const getOrganizations = () => request.get("/module3/org");
export const createCollege = (d) => request.post("/module3/org/colleges", d);
export const createMajor = (d) => request.post("/module3/org/majors", d);
export const createOrgClass = (d) => request.post("/module3/org/classes", d);
export const deleteCollege = (id) => request.delete(`/module3/org/colleges/${id}`);
export const deleteMajor = (id) => request.delete(`/module3/org/majors/${id}`);
export const deleteOrgClass = (id) => request.delete(`/module3/org/classes/${id}`);
